global:
  tftp_listen_addr: 127.0.0.1:69
  http_listen_addr: 127.0.0.1:8080
  #https_listen_addr: 127.0.0.1:443
ipfs:
  ipget_cmd:  extra/ipget
  ipfs_peer:  192.168.1.6
boot:
  kernel_cid: QmUDFQEw9M8UWrejKsfHcTVibB9ykysVQxL8NyxM2PF4uz
  initrd_cid: QmUqX5N9Aw7bXzK7kqEWv9QV5f9R11GCkXvtmCYF7wNAsj
  loader_cid: QmXpGAyGjbVbxtH49jVC17KYVuqktp4PwXiVPzLAHtSjbn
  loader_lib_cid: QmZ9KYCXZ51Nd114rBx6yM4jTYZMqTG4ZiLfLjySE5PHKn
